title: Haenyi
lang: UTF-8
description: 개발공부 기록

## local method ##
# theme: rundocs/jekyll-rtd-theme
# debug:
#   compress: false
#   dist: true
#   shortcodes: true

## remote method ##
# remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  
google:
  analytics: G-8PC93WST9C
  gtag: G-RLCK2LGGJL
  adsense: ca-pub-2279095319488155


disqus_url: http://disqus.com/by/haenyilee
disqus_id: haenyilee
